export const GET_VIDEOS_REQUEST = "GET_VIDEOS_REQUEST";
export const GET_VIDEOS_SUCCESS = "GET_VIDEOS_SUCCESS";
export const GET_VIDEOS_FAILURE = "GET_VIDEOS_FAILURE";

export const MARK_VIDEO_COMPLETE_REQUEST = "MARK_VIDEO_COMPLETE_REQUEST";
export const MARK_VIDEO_COMPLETE_SUCCESS = "MARK_VIDEO_COMPLETE_SUCCESS";
export const MARK_VIDEO_COMPLETE_FAILURE = "MARK_VIDEO_COMPLETE_FAILURE";

export const UPDATE_VIDEO_WATCH_REQUEST = "UPDATE_VIDEO_WATCH_REQUEST";
export const UPDATE_VIDEO_WATCH_SUCCESS = "UPDATE_VIDEO_WATCH_SUCCESS";
export const UPDATE_VIDEO_WATCH_FAILURE = "UPDATE_VIDEO_WATCH_FAILURE";